---@diagnostic disable: undefined-global
local yabai = function(args, completion, streamout)
	local yabai_output = ""
	local yabai_error = ""
	-- Runs in background very fast
	local yabai_task = hs.task.new("/opt/homebrew/bin/yabai", function(err, stdout, stderr)
		print("err" .. err, "stdout:" .. stdout, "stderr:" .. stderr)
	end, function(_, stdout, stderr) -- _ is task
		print("stdout:" .. stdout, "stderr:" .. stderr)
		if stdout ~= nil then
			yabai_output = yabai_output .. stdout
		end
		if stderr ~= nil then
			yabai_error = yabai_error .. stderr
		end
		if type(streamout) == "function" then
			streamout(stdout)
		end
		return true
	end, args)

	if type(completion) == "function" then
		yabai_task:setCallback(function()
			completion(yabai_output, yabai_error)
		end)
	end
	yabai_task:start()
end

--[ Yabai Config]------------------------------------------------------
BaseSuper = "alt"
Super = { "ctrl", "alt" }
AppendSuper = { "ctrl", "shift", "alt" }
local mouseJump = require("mouseJump")

--# change window focus to direction
hs.hotkey.bind(BaseSuper, "l", function()
	--yabai({ "-m", "window", "--focus", "east" })
	hs.window.filter.focusEast()
	mouseJump.toCenterOfWindow(true)
end)
hs.hotkey.bind(BaseSuper, "h", function()
	--yabai({ "-m", "window", "--focus", "west" })
	hs.window.filter.focusWest()
	mouseJump.toCenterOfWindow(true)
end)
hs.hotkey.bind(BaseSuper, "k", function()
	--yabai({ "-m", "window", "--focus", "north" })
	hs.window.filter.focusNorth()
	mouseJump.toCenterOfWindow(true)
end)
hs.hotkey.bind(BaseSuper, "j", function()
	--yabai({ "-m", "window", "--focus", "south" })
	hs.window.filter.focusSouth()
	mouseJump.toCenterOfWindow(true)
end)
hs.hotkey.bind(BaseSuper, "r", function()
	yabai({ "-m", "window", "--focus", "recent" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "tab", function()
	yabai({ "-m", "space", "--focus", "recent" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "1", function()
	yabai({ "-m", "space", "--focus", "1" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "2", function()
	yabai({ "-m", "space", "--focus", "2" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "3", function()
	yabai({ "-m", "space", "--focus", "3" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "4", function()
	yabai({ "-m", "space", "--focus", "4" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "5", function()
	yabai({ "-m", "space", "--focus", "5" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "6", function()
	yabai({ "-m", "space", "--focus", "6" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "7", function()
	yabai({ "-m", "space", "--focus", "7" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "8", function()
	yabai({ "-m", "space", "--focus", "8" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "9", function()
	yabai({ "-m", "space", "--focus", "9" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(BaseSuper, "0", function()
	yabai({ "-m", "space", "--focus", "10" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(Super, "n", function()
	yabai({ "-m", "space", "--create" }, function()
		yabai({ "-m", "query", "--spaces", "--display" }, nil, function(stdout)
			local space = hs.json.decode(stdout)
			local l = 0
			for _, _ in pairs(space) do
				l = l + 1
			end
			--print(space[l]["index"])
			local target_index = space[l]["index"]
			print(target_index)
			yabai({ "-m", "window", "--space", tostring(target_index) }, function()
				yabai({ "-m", "space", "--focus", tostring(target_index) })
				mouseJump.toCenterOfWindow()
			end)
			return true
		end)
	end)
end)
hs.hotkey.bind(Super, "w", function()
	yabai({ "-m", "space", "--destroy" }, function()
		mouseJump.toCenterOfWindow()
	end)
end)
hs.hotkey.bind(Super, "1", function()
	yabai({ "-m", "window", "--space", "1" }, function()
		yabai({ "-m", "space", "--focus", "1" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(Super, "2", function()
	yabai({ "-m", "window", "--space", "2" }, function()
		yabai({ "-m", "space", "--focus", "2" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(Super, "3", function()
	yabai({ "-m", "window", "--space", "3" }, function()
		yabai({ "-m", "space", "--focus", "3" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(Super, "4", function()
	yabai({ "-m", "window", "--space", "4" }, function()
		yabai({ "-m", "space", "--focus", "4" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(Super, "5", function()
	yabai({ "-m", "window", "--space", "5" }, function()
		yabai({ "-m", "space", "--focus", "5" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(Super, "6", function()
	yabai({ "-m", "window", "--space", "6" }, function()
		yabai({ "-m", "space", "--focus", "6" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(Super, "7", function()
	yabai({ "-m", "window", "--space", "7" }, function()
		yabai({ "-m", "space", "--focus", "7" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(Super, "8", function()
	yabai({ "-m", "window", "--space", "8" }, function()
		yabai({ "-m", "space", "--focus", "8" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(Super, "9", function()
	yabai({ "-m", "window", "--space", "9" }, function()
		yabai({ "-m", "space", "--focus", "9" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(Super, "0", function()
	yabai({ "-m", "window", "--space", "10" }, function()
		yabai({ "-m", "space", "--focus", "10" }, function()
			mouseJump.toCenterOfWindow()
		end)
	end)
end)
hs.hotkey.bind(AppendSuper, "1", function()
	yabai({ "-m", "window", "--space", "1" })
end)
hs.hotkey.bind(AppendSuper, "2", function()
	yabai({ "-m", "window", "--space", "2" })
end)
hs.hotkey.bind(AppendSuper, "3", function()
	yabai({ "-m", "window", "--space", "3" })
end)
hs.hotkey.bind(AppendSuper, "4", function()
	yabai({ "-m", "window", "--space", "4" })
end)
hs.hotkey.bind(AppendSuper, "5", function()
	yabai({ "-m", "window", "--space", "5" })
end)
hs.hotkey.bind(AppendSuper, "6", function()
	yabai({ "-m", "window", "--space", "6" })
end)
hs.hotkey.bind(AppendSuper, "7", function()
	yabai({ "-m", "window", "--space", "7" })
end)
hs.hotkey.bind(AppendSuper, "8", function()
	yabai({ "-m", "window", "--space", "8" })
end)
hs.hotkey.bind(AppendSuper, "9", function()
	yabai({ "-m", "window", "--space", "9" })
end)
hs.hotkey.bind(AppendSuper, "0", function()
	yabai({ "-m", "window", "--space", "10" })
end)
hs.hotkey.bind(Super, "z", function()
	yabai({ "-m", "window", "--display", "next" })
end)
hs.hotkey.bind(Super, "l", function()
	yabai({ "-m", "window", "--warp", "east" })
end)
hs.hotkey.bind(Super, "h", function()
	yabai({ "-m", "window", "--warp", "west" })
end)
hs.hotkey.bind(Super, "k", function()
	yabai({ "-m", "window", "--warp", "north" })
end)
hs.hotkey.bind(Super, "j", function()
	yabai({ "-m", "window", "--warp", "south" })
end)
hs.hotkey.bind(Super, "z", function()
	yabai({ "-m", "space", "--balance" })
end)
hs.hotkey.bind(Super, "f", function()
	yabai({ "-m", "window", "--toggle", "zoom-fullscreen" })
end)
--[ END Yabai Config]------------------------------------------------------

return yabai
